# config/packages/fos_user.yaml
fos_user:
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: App\Entity\User
  from_email:
    address: "evaldas.vaitonis@gmail.com"
    sender_name: "evaldas.vaitonis@gmail.com"