homepage:
    path: /
    controller: App\Controller\HomeController::index
register_route:
  path: /reg
  controller: App\Controller\RouteRegistrationController:index
save_route:
  path: /route-save
  controller: App\Controller\RouteRegistrationController:store
matches:
  path: /matches
  controller: App\Controller\MatchController:index
login_redirect:
  path: /login-redirect
  controller: App\Controller\RedirectController:redirectAfterLogin
security_logout:
  path: /logout
  methods: GET
login:
  path: /login
