#index:
#    path: /
#    controller: App\Controller\DefaultController::index
register_route:
  path: /reg
  controller: App\Controller\RouteRegistrationController:index
save_route:
  path: /route-save
  controller: App\Controller\RouteRegistrationController:store
tryout:
  path: /tryout
  controller: App\Controller\TryoutController:index
matches:
  path: /matches
  controller: App\Controller\MatchController:index
login_redirect:
  path: /login-redirect
  controller: App\Controller\RedirectController:redirectAfterLogin